//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPLib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FightDetail
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> HeadCount { get; set; }
        public Nullable<int> BodyCount { get; set; }
        public Nullable<System.DateTime> PartTime { get; set; }
        public Nullable<System.DateTime> ExitTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string FightId { get; set; }
        public string StageId { get; set; }
    
        public virtual FightInfo FightInfo { get; set; }
    }
}
