//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPLib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfoSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfoSet()
        {
            this.UserSessionSet = new HashSet<UserSessionSet>();
            this.DefaultStage = new HashSet<DefaultStage>();
        }
    
        public string Id { get; set; }
        public string WId { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string Pwd { get; set; }
        public string DefaultStageId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSessionSet> UserSessionSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefaultStage> DefaultStage { get; set; }
    }
}
